// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c6b5ff88-7fd2-4244-8ce8-cb68e31a1773",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_RtNCwZIX5",
    "aws_user_pools_web_client_id": "6ttcti4uj2n1ncm1srvscv4pod",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4jneureytndzndahiwj4np46ty.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v3hq3nzhdvgobdme7k3in7ygqe"
};


export default awsmobile;
